# pull official Amazon Linux 2023 base image
FROM amazonlinux:2023

# set work directory
#RUN mkdir /usr/src/inquisitive_bookworm_club
WORKDIR /usr/src

#default port used by Django Web Applications
EXPOSE 8000

# set environment variables
#ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
#RUN pip install --upgrade pip
#COPY ./requirements.txt .
#RUN pip install -r requirements.txt

# copy project
COPY inquisitive_bookworm_club /usr/src/inquisitive_bookworm_club

# change working directory
WORKDIR /usr/src/inquisitive_bookworm_club
