apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquisitivebookwormclub
  namespace: bpb-aws-book
  labels:
    app: inquisitivebookwormclub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inquisitivebookwormclub
  template:
    metadata:
      labels:
        app: inquisitivebookwormclub
    spec:
      serviceAccountName: bpb-aws-book-sa
      containers:
        - name: inquisitivebookwormclubcontainer
          image: 111111111111.dkr.ecr.AWS-REGION.amazonaws.com/bpbbook/inquisitivebookwormclubrepo:latest
          ports:
            - containerPort: 80    
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /             
              port: 80           
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /            
              port: 80          
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: inquisitivebookwormclub-service
  namespace: bpb-aws-book
spec:
  type: NodePort 
  ports:
    - port: 80
      targetPort: 80    
      protocol: TCP
  selector:
    app: inquisitivebookwormclub 
