apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquisitivebookwormclub
  namespace: bpb-aws-book
  labels:
    app: inquisitivebookwormclub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inquisitivebookwormclub
  template:
    metadata:
      labels:
        app: inquisitivebookwormclub
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80    
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /             
              port: 80           
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /            
              port: 80          
            initialDelaySeconds: 15
            periodSeconds: 20
