apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquisitivebookwormclub-deployment
  namespace: bpb-aws-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inquisitivebookwormclub-app
  template:
    metadata:
      labels:
        app: inquisitivebookwormclub-app
    spec:
      serviceAccountName: bpb-aws-book-sa
      containers:
      - name: inquisitivebookwormclubcontainer
        image: 449792353570.dkr.ecr.us-east-1.amazonaws.com/bpbbook/inquisitivebookwormclubrepo:latest
        ports:
        - containerPort: 80
          name: containerport

---
apiVersion: v1
kind: Service
metadata:
  name: inquisitivebookwormclub-app
  namespace: bpb-aws-book
spec:
  type: NodePort
  selector:
    app: inquisitivebookwormclub-app
  ports:
  - name: inquisitivebookwormclub-service-port
    protocol: TCP
    port: 80
    targetPort: containerport
