apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquisitivebookwormclub-deployment
  namespace: bpb-aws-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inquisitivebookwormclub-app
  template:
    metadata:
      labels:
        app: inquisitivebookwormclub-app
    spec:
      serviceAccountName: bpb-aws-book-sa
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 169.254.20.10  # VPC DNS
        searches:
          - us-east-1.compute.internal
      containers:
      - name: inquisitivebookwormclubcontainer
        image: <Your AWS Account>.dkr.ecr.<AWS REGION>.amazonaws.com/bpbbook/inquisitivebookwormclubrepo:latest
        ports:
        - containerPort: 80
          name: containerport

---
apiVersion: v1
kind: Service
metadata:
  name: inquisitivebookwormclub-app
  namespace: bpb-aws-book
spec:
  type: LoadBalancer
  selector:
    app: inquisitivebookwormclub-app
  ports:
  - name: inquisitivebookwormclub-service-port
    protocol: TCP
    port: 80
    targetPort: containerport
