apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: bpb-aws-book 
  labels:
    app: inquisitivebookwormclubapp
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: nginx-svc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquisitivebookwormclub-deployment
  labels:
    app: inquisitivebookwormclub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bpb-aws-book
spec:
  selector:
    app: inquisitivebookwormclub
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: nginx-svc
