apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: bpb-aws-book 
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: simple-nginx-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bpb-aws-book
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: simple-nginx-svc
