apiVersion: v1
kind: Pod
metadata:
  name: inquisitivebookwormclubpod
  namespace: bpb-aws-book 
  labels:
    app.kubernetes.io/name: proxy
spec:
  serviceAccountName: default
  containers:
  - name: inquisitivebookwormclubcontainer
    image: xxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/bpbbook/inquisitivebookwormclubrepo:latest
    ports:
      - containerPort: 80
        name: containerport

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bpb-aws-book
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: containerport
